In [4]:
import torch
(x_train, y_train, x_test, y_test)=torch.load('cifar10.pt')

In [5]:
#set datatype as float
x_train=x_train.type(torch.FloatTensor)
x_test =x_test.type(torch.FloatTensor)
y_test =y_test.type(torch.FloatTensor)
y_train =y_train.type(torch.FloatTensor)
#size of train and test samples
s1=x_train.shape
s2=x_test.shape



In [6]:
#initializing
b=torch.zeros(s1[0],256,3)
c=torch.zeros(s2[0],256,3)
# histogram of test and train sample
 
for i  in range(1000):
    
    for k in range(s1[1]):
        for l in range(s1[2]):
            for j in range(s1[3]):
                a=0;
                a=x_train[i,k,l,j]
                a=int(a)
                b[i,a,j]=b[i,a,j]+1
                
                if i<=s2[0]-1:
                    a1=0;
                    a1=x_test[i,k,l,j]
                    a1=int(a1)
                    c[i,a1,j]=c[i,a1,j]+1

In [7]:
#reshaping
b1=b.reshape(1000,256*3)
b2=c.reshape(100,256*3)


In [23]:

d=torch.zeros(s1[0],s2[0])
# finding euclidean distance
for i in range(s1[0]):
    for j in range(s2[0]):
        d[i,j]=torch.dist(b1[i],b2[j],2)

In [24]:
d1=torch.sort(d,0)
d2=torch.tensor(d1[1])
indices=torch.tensor([0])
#KNN for K=1
d3=torch.index_select(d2,0,indices)

C:\Users\archana\Anaconda3\lib\site-packages\ipykernel_launcher.py:2: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  


In [25]:
e=torch.zeros(s2[0])
for ii in range(s2[0]):
    e[ii]=y_train[d3[0,ii]]

In [26]:
#import sklearn library
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
# confusion matrix and accuracy
f3=confusion_matrix(y_test,e)
print(f3)
f5=accuracy_score(y_test,e)
print(f5)

[[2 1 0 1 1 0 4 0 1 0]
 [0 2 0 0 0 1 0 0 1 2]
 [0 3 1 1 1 1 0 0 0 1]
 [0 1 0 0 1 1 2 1 0 4]
 [0 0 2 2 0 2 1 0 0 0]
 [0 2 1 1 0 1 2 0 0 1]
 [0 0 0 3 3 0 8 2 0 0]
 [1 1 0 1 1 1 1 3 0 2]
 [5 1 0 3 0 0 1 0 1 2]
 [0 2 0 1 1 1 1 0 1 4]]
0.22


In [29]:
indices1=torch.tensor([0,1,2])
d31=torch.index_select(d2,0,indices1)

In [39]:
# KNN for K=3
h=torch.zeros(3,s2[0])
h1=torch.zeros(s2[0])
for m in range(s2[0]):
    for n in range(3):
        h[n,m]=y_train[d31[n,m]]
    
    if h[0,m]==h[1,m] and h[0,m]==h[2,m]: 
       h1[m]=h[0,m]
    elif h[1,m]==h[2,m] and h[1,m]==h[0,m]:
         h1[m]=h[1,m]
        
    elif   h[2,m]==h[1,m] and h[2,m]==h[0,m]:
             h1[m]=h[2,m]
    #else:
     #  h1[m] =y_train[d3[0,m]]   
f21=confusion_matrix(y_test,h1)
f51=accuracy_score(y_test,h1)

In [40]:
print(f21)
print(f51)

[[10  0  0  0  0  0  0  0  0  0]
 [ 6  0  0  0  0  0  0  0  0  0]
 [ 8  0  0  0  0  0  0  0  0  0]
 [10  0  0  0  0  0  0  0  0  0]
 [ 7  0  0  0  0  0  0  0  0  0]
 [ 8  0  0  0  0  0  0  0  0  0]
 [15  0  0  0  1  0  0  0  0  0]
 [10  0  0  0  0  0  0  0  0  1]
 [13  0  0  0  0  0  0  0  0  0]
 [ 9  0  0  1  0  0  0  0  0  1]]
0.11


In [41]:
#KNN for K=5
indices2=torch.tensor([0,1,2,3,4])
d32=torch.index_select(d2,0,indices2)
h3=torch.zeros(5,s2[0])
h2=torch.zeros(s2[0])
count2=0
for m in range(s2[0]):
    for n in range(5):
        h3[n,m]=y_train[d32[n,m]]
        for z1 in range(5):
            count2=0
            for z in range(5):
                if  z1!=z and h3[z1,m]==h3[z,m]:
                     count2=count2+1
                if count2 >=3:
                   h2[m]=h3[z1,m]
f31=confusion_matrix(y_test,h2)
f61=accuracy_score(y_test,h2)
print(f31)
print(f61)

[[10  0  0  0  0  0  0  0  0  0]
 [ 6  0  0  0  0  0  0  0  0  0]
 [ 7  1  0  0  0  0  0  0  0  0]
 [10  0  0  0  0  0  0  0  0  0]
 [ 6  0  0  0  0  0  1  0  0  0]
 [ 8  0  0  0  0  0  0  0  0  0]
 [15  0  0  0  1  0  0  0  0  0]
 [10  0  0  0  0  0  0  0  0  1]
 [13  0  0  0  0  0  0  0  0  0]
 [11  0  0  0  0  0  0  0  0  0]]
0.1
