In [7]:
import torch
(x_train, y_train, x_test, y_test)=torch.load('mnist.pt')

# Set the datatype as float

x_train=x_train.type(torch.FloatTensor)
x_test =x_test.type(torch.FloatTensor)
y_test =y_test.type(torch.FloatTensor)
y_train =y_train.type(torch.FloatTensor)
# size of training data and test data
a=x_train.shape
b=x_test.shape
#Initializing 'c'
c=torch.zeros(a[0],b[0])
#finding eucledian distance between train and test
for i in range(a[0]):
   for j in range(b[0]):
        c[i,j]=torch.dist(torch.reshape(x_train[i],[1,a[1]*a[2]]),torch.reshape(x_test[j],[1,a[1]*a[2]]),2)
#KNN classifier for K=1
d=torch.kthvalue(c,1,0)
e=torch.zeros(b[0])
g=d[1]
count1=0
for l in range(b[0]):
    e[l]=y_train[g[l]]
    if e[l]==y_test[l]:
       count1=count1+1
#loading 'sklearn'library
from sklearn.metrics import confusion_matrix
from sklearn.metrics import accuracy_score
# confusion matrix and and accuracy measure 
f1=confusion_matrix(y_test,e)
print(f1)
f4=accuracy_score(y_test,e)
print(f4)
# KNN for K=3
d1=torch.sort(c,0)
d2=torch.tensor(d1[1])
indices=torch.tensor([0,1,2])
d3=torch.index_select(d2,0,indices)
h=torch.zeros(3,b[0])
h1=torch.zeros(b[0])
#Searching for majority label
for m in range(b[0]):
    for n in range(3):
        h[n,m]=y_train[d3[n,m]]
    
    if h[0,m]==h[1,m] and h[0,m]==h[2,m]: 
       h1[m]=h[0,m]
    elif h[1,m]==h[2,m] and h[1,m]==h[0,m]:
         h1[m]=h[1,m]
        
    elif   h[2,m]==h[1,m] and h[2,m]==h[0,m]:
             h1[m]=h[2,m]
    #else:
     #  h1[m] =y_train[d3[0,m]]   
f2=confusion_matrix(y_test,h1)
f5=accuracy_score(y_test,h1)
print(f2)
print(f5)
## KNN for K=5
indices1=torch.tensor([0,1,2,3,4])
d31=torch.index_select(d2,0,indices1)
h3=torch.zeros(5,b[0])
h2=torch.zeros(b[0])
count2=0
for m in range(b[0]):
    for n in range(5):
        h3[n,m]=y_train[d31[n,m]]
        for z1 in range(5):
            for z in range(5):
                if  z1!=z and h3[z1,m]==h3[z,m]:
                     count2=count2+1
                if count2 >= 3:
                   h2[m]=h3[z1,m]
  
f3=confusion_matrix(y_test,h2)
f6=accuracy_score(y_test,h2)
print(f3)
print(f6)

[[ 8  0  0  0  0  0  0  0  0  0]
 [ 0 14  0  0  0  0  0  0  0  0]
 [ 0  0  7  1  0  0  0  0  0  0]
 [ 0  0  0  8  0  2  0  0  0  1]
 [ 0  0  0  0 10  0  0  0  0  4]
 [ 0  1  0  1  1  4  0  0  0  0]
 [ 2  0  0  0  0  0  8  0  0  0]
 [ 0  0  0  0  0  0  0 14  0  1]
 [ 0  0  1  0  0  0  0  0  1  0]
 [ 0  0  0  0  1  0  0  1  0  9]]
0.83
[[ 8  0  0  0  0  0  0  0  0  0]
 [ 0 14  0  0  0  0  0  0  0  0]
 [ 6  0  2  0  0  0  0  0  0  0]
 [ 4  0  0  6  0  0  0  0  0  1]
 [ 7  0  0  0  6  0  0  0  0  1]
 [ 4  0  0  0  0  3  0  0  0  0]
 [ 5  0  0  0  0  0  5  0  0  0]
 [ 3  0  0  0  0  0  0 12  0  0]
 [ 1  0  0  0  0  0  0  0  1  0]
 [ 4  0  0  0  0  0  0  0  0  7]]
0.64


C:\Users\archana\Anaconda3\lib\site-packages\ipykernel_launcher.py:31: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).


[[ 8  0  0  0  0  0  0  0  0  0]
 [ 0 14  0  0  0  0  0  0  0  0]
 [ 0  1  5  0  1  0  0  1  0  0]
 [ 0  1  1  6  1  2  0  0  0  0]
 [ 1  0  0  0  9  0  0  1  0  3]
 [ 0  1  0  1  2  2  0  0  0  1]
 [ 0  1  0  0  0  0  9  0  0  0]
 [ 0  1  0  0  0  0  0 13  0  1]
 [ 0  0  0  0  0  0  0  0  2  0]
 [ 0  0  0  0  4  0  0  1  0  6]]
0.74
